eureka:
  instance:
    host: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      override.system-properties: false

management:
  zipkin:
    tracing:
      endpoint: http://192.168.1.90:9411/api/v2/spans
      sampling:
        probability: 1.0 # range is between 0 and 1