spring:
  datasource:
    url: jdbc:postgresql://192.168.1.90:5432/payment
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: payment-service

  kafka:
    bootstrap-servers: 192.168.1.90:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:in.dchandwani.ecommerce.kafka.payment.PaymentNotificationRequest

server:
  port: 8060

